# Generated by Django 5.1.15 on 2026-10-07 11:18

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_boundaries(apps, schema_editor):
    state_model = apps.get_model('users', 'UserSessionVersion')
    boundary_model = apps.get_model('users', 'UserSessionRevocationBoundary')
    using = schema_editor.connection.alias
    batch = []
    for user_id, version in state_model.objects.using(using).values_list('user_id', 'version').iterator(chunk_size=1000):
        batch.append(boundary_model(user_id=user_id, version=version))
        if len(batch) == 1000:
            boundary_model.objects.using(using).bulk_create(batch)
            batch.clear()
    if batch:
        boundary_model.objects.using(using).bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_locale_preference"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSessionRevocationBoundary",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="session_revocation_boundary",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=0, editable=False)),
            ],
            options={
                "db_table": "htx_user_session_revocation_boundary",
            },
        ),
        migrations.CreateModel(
            name="SessionRevocationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        default="browser_session_revoked", editable=False, max_length=32
                    ),
                ),
                (
                    "revocation_type",
                    models.CharField(default="user", editable=False, max_length=16),
                ),
                (
                    "actor_type",
                    models.CharField(default="human", editable=False, max_length=16),
                ),
                ("actor_user_id", models.PositiveBigIntegerField(editable=False)),
                (
                    "target_user_id",
                    models.PositiveBigIntegerField(db_index=True, editable=False),
                ),
                ("reason_code", models.CharField(editable=False, max_length=32)),
                ("security_version", models.PositiveBigIntegerField(editable=False)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
            ],
            options={
                "db_table": "htx_session_revocation_event",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_user_id", "security_version"),
                        name="unique_session_revocation_event",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_boundaries, migrations.RunPython.noop),
    ]
